### ISSUE TITLE
Potentially modifying configs during imports

### ISSUE THREAD

**Issue by adam-vessey** [roblib/islandora_fits#13]
[`hook_install()`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_install/9.3.x) has an `$is_syncing` boolean flag that's passed, for which the documentation indicates that:

> [`hook_install()` implementations] should not make any changes to configuration objects or entities.

This module [presently attempts to (conditionally) add a file extension to the validation of a field](https://github.com/roblib/islandora_fits/blob/791028e658959b98091ba7999ca332001a104fd6/islandora_fits.install#L28-L38), which constitutes a change to a config entity, which it apparently shouldn't be doing.

... a message warning of its absence from `hook_install()` during config imports (requiring similar awareness that config may not be fully imported when it is executed) and/or an [implementation of `hook_requirements()`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_requirements/9.3.x), and links to where the change might be made manually (or some route to do it automatically), such that the change can be made out of band may be in order?

**Comment by adam-vessey** [comment]
Actually, looking into this a bit more... is this adjustment of configuration even necessary? The config/field being changed is `media.file.field_media_file`; however, we use our own `fits_technical_metadata` bundle here, not `file` (the field ID of `media.fits_technical_metadata.field_media_file`)... despite both possibly using the same `field.storage.media.field_media_file` storage under the hood, I'm not sure that the extensions allowed under the `file` bundle are really relevant for what happens in the `fits_technical_metadata` bundle?

... it's really not clear... digging back to where the change was introduced: https://github.com/roblib/islandora_fits/commit/24d8fef58d290b8dac173f0b484acf0dd88497eb ... [it appears that `media.fits_technical_metadata.field_media_file` existed at that time](https://github.com/roblib/islandora_fits/blob/24d8fef58d290b8dac173f0b484acf0dd88497eb/config/install/field.field.media.fits_technical_metadata.field_media_file.yml) and [the action was configured](https://github.com/roblib/islandora_fits/blob/24d8fef58d290b8dac173f0b484acf0dd88497eb/config/install/system.action.generate_a_technical_metadata_derivative.yml#L17) to [target it](https://github.com/roblib/islandora_fits/blob/24d8fef58d290b8dac173f0b484acf0dd88497eb/config/install/media.type.fits_technical_metadata.yml#L11), but this change was still made... so maybe there's a part of the picture that I'm missing?

**Comment by adam-vessey** [comment]
Yeah, just successfully had FITS generated into a `fits_technical_metadata` media entity (as the installed configuration makes happen), without having `xml` in `media.file.field_media_file`... which has me thinking the setting in `media.file.field_media_file` is just vestigial, and can probably be dropped.

**Comment by rosiel** [comment]
@adam-vessey is this ready to close?

**Comment by adam-vessey** [comment]
I believe so.
